### ISSUE TITLE
Android SSL

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/openmsupply#2]
Would like to implement SSL for the API communication between web app and API.
Refer to
- https://github.com/openmsupply/openmsupply-client/pull/1238
- https://github.com/openmsupply/remote-server/pull/1086
- https://github.com/openmsupply/remote-server/issues/1070

**Comment by andreievg** [comment]
@clemens-msupply can this one be closed ?

**Comment by clemens-msupply** [comment]
yes, this is done now

@mark-prins do I have access to this repo? (can't close the issue)
